- name: Configure Docker on EC2 Instances
  hosts: all                # Target all hosts in the Ansible inventory.
  become: true              # Run all tasks with elevated privileges (sudo).
  connection: ssh           # Use SSH for remote connection to the hosts.

  tasks:
    - name: Update apt package index
      command: sudo apt-get update
      # Refreshes the list of available packages and their versions.
      # Suggestion: Use the `apt` module with `update_cache: yes` for better idempotency.

    - name: Install Docker
      command: sudo apt-get install -y docker.io
      # Installs Docker using the system package manager.
      # Suggestion: Use the `apt` module with `name: docker.io` for Ansible-native handling.

    - name: Start Docker service
      command: sudo systemctl start docker
      # Starts the Docker service.
      # Suggestion: Use the `service` module for clearer intent and service management.

    - name: Deploy Docker container
      command: docker run -itd -p 8084:8081 meghaviveki/financeme-backend:{{ docker_image_tag }}
      # Runs the container in detached mode and maps port 8084 on the host to 8081 in the container.
      # `docker_image_tag` should be passed via `--extra-vars`.
      # Suggestion: Use the `community.docker.docker_container` module for structured container deployment.
